global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
        labels:
          hostname: compute1

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          hostname: compute1

  - job_name: 'libvirt'
    scrape_interval: 5s
    static_configs:
      - targets: ['libvirt:9177']
        labels:
          hostname: compute1

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          hostname: compute1

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
        labels:
          hostname: compute1

  # This job is used to scrape from another prometheus instance
  - job_name: 'federate-controller'
    scrape_interval: 5s
    honor_labels: true
    metrics_path: '/federate'
    basic_auth:
      username: admin
      password: admin
    params:
      'match[]':
        # matches every job from the other prometheus instance
        - '{job=~".+"}'
    static_configs:
      - targets: ['192.168.162.50:9090']
        labels:
          # adds the label hostname if it is not set yet
          hostname: controller

  # This job is used to scrape from another prometheus instance
  - job_name: 'federate-compute2'
    scrape_interval: 5s
    honor_labels: true
    metrics_path: '/federate'
    basic_auth:
      username: admin
      password: admin
    params:
      'match[]':
        # matches every job from the other prometheus instance
        - '{job=~".+"}'
    static_configs:
      - targets: ['192.168.162.50:9090']
        labels:
          # adds the label hostname if it is not set yet
          hostname: compute2

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
